In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv('Bengaluru_House_Data.csv')

In [3]:
data.head()

,area_type,availability,location,size,society,total_sqft,bath,balcony,price
0,Super built-up Area,19-Dec,Electronic City Phase II,2 BHK,Coomee,1056,2.0,1.0,39.07
1,Plot Area,Ready To Move,Chikka Tirupathi,4 Bedroom,Theanmp,2600,5.0,3.0,120.00
2,Built-up Area,Ready To Move,Uttarahalli,3 BHK,NaN,1440,2.0,3.0,62.00
3,Super built-up Area,Ready To Move,Lingadheeranahalli,3 BHK,Soiewre,1521,3.0,1.0,95.00
4,Super built-up Area,Ready To Move,Kothanur,2 BHK,NaN,1200,2.0,1.0,51.00

In [4]:
data.shape

(13320, 9)

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13320 entries, 0 to 13319
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   area_type     13320 non-null  object
 1   availability  13320 non-null  object
 2   location      13319 non-null  object
 3   size          13304 non-null  object
 4   society       7818 non-null   object
 5   total_sqft    13320 non-null  object
 6   bath          13247 non-null  float64
 7   balcony       12711 non-null  float64
 8   price         13320 non-null  float64
dtypes: float64(3), object(6)
memory usage: 936.7+ KB

In [6]:
for column in data.columns:
    print(data[column].value_counts())
    print("*$$###*"*10)

area_type
Super built-up  Area    8790
Built-up  Area          2418
Plot  Area              2025
Carpet  Area              87
Name: count, dtype: int64
*$$###**$$###**$$###**$$###**$$###**$$###**$$###**$$###**$$###**$$###*
availability
Ready To Move    10581
18-Dec             307
18-May             295
18-Apr             271
18-Aug             200
                 ...
16-Oct               1
17-Jan               1
16-Nov               1
16-Jan               1
14-Jul               1
Name: count, Length: 81, dtype: int64
*$$###**$$###**$$###**$$###**$$###**$$###**$$###**$$###**$$###**$$###*
location
Whitefield                         540
Sarjapur  Road                     399
Electronic City                    302
Kanakpura Road                     273
Thanisandra                        234
                                  ...
3rd Stage Raja Rajeshwari Nagar      1
Chuchangatta Colony                  1
Electronic City Phase 1,             1
Chikbasavanapura                     1
Abshot Layout                        1
Name: count, Length: 1305, dtype: int64
*$$###**$$###**$$###**$$###**$$###**$$###**$$###**$$###**$$###**$$###*
size
2 BHK         5199
3 BHK         4310
4 Bedroom      826
4 BHK          591
3 Bedroom      547
1 BHK          538
2 Bedroom      329
5 Bedroom      297
6 Bedroom      191
1 Bedroom      105
8 Bedroom       84
7 Bedroom       83
5 BHK           59
9 Bedroom       46
6 BHK           30
7 BHK           17
1 RK            13
10 Bedroom      12
9 BHK            8
8 BHK            5
11 BHK           2
10 BHK           2
11 Bedroom       2
27 BHK           1
19 BHK           1
43 Bedroom       1
16 BHK           1
14 BHK           1
12 Bedroom       1
13 BHK           1
18 Bedroom       1
Name: count, dtype: int64
*$$###**$$###**$$###**$$###**$$###**$$###**$$###**$$###**$$###**$$###*
society
GrrvaGr    80
PrarePa    76
Prtates    59
Sryalan    59
GMown E    56
           ..
SNadeAr     1
DSellil     1
Shensit     1
VKvenas     1
Vemes H     1
Name: count, Length: 2688, dtype: int64
*$$###**$$###**$$###**$$###**$$###**$$###**$$###**$$###**$$###**$$###*
total_sqft
1200           843
1100           221
1500           205
2400           196
600            180
              ...
2920             1
5665.84          1
1369             1
7150             1
1200 - 1470      1
Name: count, Length: 2117, dtype: int64
*$$###**$$###**$$###**$$###**$$###**$$###**$$###**$$###**$$###**$$###*
bath
2.0     6908
3.0     3286
4.0     1226
1.0      788
5.0      524
6.0      273
7.0      102
8.0       64
9.0       43
10.0      13
12.0       7
11.0       3
13.0       3
16.0       2
27.0       1
14.0       1
40.0       1
15.0       1
18.0       1
Name: count, dtype: int64
*$$###**$$###**$$###**$$###**$$###**$$###**$$###**$$###**$$###**$$###*
balcony
2.0    5113
1.0    4897
3.0    1672
0.0    1029
Name: count, dtype: int64
*$$###**$$###**$$###**$$###**$$###**$$###**$$###**$$###**$$###**$$###*
price
75.00    310
65.00    302
55.00    275
60.00    270
45.00    240
        ...
43.04      1
61.11      1
46.56      1
42.54      1
47.35      1
Name: count, Length: 1994, dtype: int64
*$$###**$$###**$$###**$$###**$$###**$$###**$$###**$$###**$$###**$$###*

In [7]:
data.isnull().sum()

area_type          0
availability       0
location           1
size              16
society         5502
total_sqft         0
bath              73
balcony          609
price              0
dtype: int64

In [8]:
data.drop(columns = ['area_type' , 'availability','society' , 'balcony'] , inplace = True)

In [9]:
data.describe()

               bath         price
count  13247.000000  13320.000000
mean       2.692610    112.565627
std        1.341458    148.971674
min        1.000000      8.000000
25%        2.000000     50.000000
50%        2.000000     72.000000
75%        3.000000    120.000000
max       40.000000   3600.000000

In [10]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13320 entries, 0 to 13319
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   location    13319 non-null  object
 1   size        13304 non-null  object
 2   total_sqft  13320 non-null  object
 3   bath        13247 non-null  float64
 4   price       13320 non-null  float64
dtypes: float64(2), object(3)
memory usage: 520.4+ KB

In [11]:
data['location'].value_counts()

location
Whitefield                         540
Sarjapur  Road                     399
Electronic City                    302
Kanakpura Road                     273
Thanisandra                        234
                                  ...
3rd Stage Raja Rajeshwari Nagar      1
Chuchangatta Colony                  1
Electronic City Phase 1,             1
Chikbasavanapura                     1
Abshot Layout                        1
Name: count, Length: 1305, dtype: int64

In [12]:
data['location'] =data['location'].fillna('Sarjapur Road')

In [13]:
data['size'].value_counts()

size
2 BHK         5199
3 BHK         4310
4 Bedroom      826
4 BHK          591
3 Bedroom      547
1 BHK          538
2 Bedroom      329
5 Bedroom      297
6 Bedroom      191
1 Bedroom      105
8 Bedroom       84
7 Bedroom       83
5 BHK           59
9 Bedroom       46
6 BHK           30
7 BHK           17
1 RK            13
10 Bedroom      12
9 BHK            8
8 BHK            5
11 BHK           2
10 BHK           2
11 Bedroom       2
27 BHK           1
19 BHK           1
43 Bedroom       1
16 BHK           1
14 BHK           1
12 Bedroom       1
13 BHK           1
18 Bedroom       1
Name: count, dtype: int64

In [14]:
data.isnull().sum()

location       0
size          16
total_sqft     0
bath          73
price          0
dtype: int64

In [15]:
data['bhk'] =data['size'].fillna('2 BHK')

In [16]:
data['bath'].value_counts()

bath
2.0     6908
3.0     3286
4.0     1226
1.0      788
5.0      524
6.0      273
7.0      102
8.0       64
9.0       43
10.0      13
12.0       7
11.0       3
13.0       3
16.0       2
27.0       1
14.0       1
40.0       1
15.0       1
18.0       1
Name: count, dtype: int64

In [17]:
data['bath'] = data['bath'].fillna(2.0)

In [18]:
data.isnull().sum()

location       0
size          16
total_sqft     0
bath           0
price          0
bhk            0
dtype: int64

In [19]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13320 entries, 0 to 13319
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   location    13320 non-null  object
 1   size        13304 non-null  object
 2   total_sqft  13320 non-null  object
 3   bath        13320 non-null  float64
 4   price       13320 non-null  float64
 5   bhk         13320 non-null  object
dtypes: float64(2), object(4)
memory usage: 624.5+ KB

In [20]:
data.head()

                   location       size total_sqft  bath   price        bhk
0  Electronic City Phase II      2 BHK       1056   2.0   39.07      2 BHK
1          Chikka Tirupathi  4 Bedroom       2600   5.0  120.00  4 Bedroom
2               Uttarahalli      3 BHK       1440   2.0   62.00      3 BHK
3        Lingadheeranahalli      3 BHK       1521   3.0   95.00      3 BHK
4                  Kothanur      2 BHK       1200   2.0   51.00      2 BHK

In [21]:
data['size'].unique()

array(['2 BHK', '4 Bedroom', '3 BHK', '4 BHK', '6 Bedroom', '3 Bedroom',
       '1 BHK', '1 RK', '1 Bedroom', '8 Bedroom', '2 Bedroom',
       '7 Bedroom', '5 BHK', '7 BHK', '6 BHK', '5 Bedroom', '11 BHK',
       '9 BHK', nan, '9 Bedroom', '27 BHK', '10 Bedroom', '11 Bedroom',
       '10 BHK', '19 BHK', '16 BHK', '43 Bedroom', '14 BHK', '8 BHK',
       '12 Bedroom', '13 BHK', '18 Bedroom'], dtype=object)

In [22]:
#data['bhk'] = data['size'].str.split().str.get(0).astype(int)
data['bhk'] = data['size'].str.extract(r'(\d+)')
data['bhk'] = pd.to_numeric(data['bhk'], errors='coerce')

In [23]:
data[data.bhk >20]

                       location        size total_sqft  bath  price   bhk
1718  2Electronic City Phase II      27 BHK       8000  27.0  230.0  27.0
4684                Munnekollal  43 Bedroom       2400  40.0  660.0  43.0

In [24]:
data['total_sqft'].unique()

array(['1056', '2600', '1440', ..., '1133 - 1384', '774', '4689'],
      dtype=object)

In [25]:
def convertdRange(x):
    try:
        if '-' in str(x):
            low, high = x.split('-')
            return (float(low) + float(high)) / 2
        return float(x)
    except:
        return None

In [26]:
data['total_sqft'] =data['total_sqft'].apply(convertdRange)

In [27]:
data.head()

                   location       size  total_sqft  bath   price  bhk
0  Electronic City Phase II      2 BHK      1056.0   2.0   39.07  2.0
1          Chikka Tirupathi  4 Bedroom      2600.0   5.0  120.00  4.0
2               Uttarahalli      3 BHK      1440.0   2.0   62.00  3.0
3        Lingadheeranahalli      3 BHK      1521.0   3.0   95.00  3.0
4                  Kothanur      2 BHK      1200.0   2.0   51.00  2.0

In [28]:
#price prediction
data['price_per_sqft'] = data['price'] * 100000 / data['total_sqft']

In [29]:
data['price_per_sqft']

0         3699.810606
1         4615.384615
2         4305.555556
3         6245.890861
4         4250.000000
             ...
13315     6689.834926
13316    11111.111111
13317     5258.545136
13318    10407.336319
13319     3090.909091
Name: price_per_sqft, Length: 13320, dtype: float64

In [30]:
 data.describe()

         total_sqft          bath         price           bhk  price_per_sqft
count  13274.000000  13320.000000  13320.000000  13304.000000    1.327400e+04
mean    1559.626694      2.688814    112.565627      2.803743    7.907501e+03
std     1238.405258      1.338754    148.971674      1.294974    1.064296e+05
min        1.000000      1.000000      8.000000      1.000000    2.678298e+02
25%     1100.000000      2.000000     50.000000      2.000000    4.266865e+03
50%     1276.000000      2.000000     72.000000      3.000000    5.434306e+03
75%     1680.000000      3.000000    120.000000      3.000000    7.311746e+03
max    52272.000000     40.000000   3600.000000     43.000000    1.200000e+07

In [31]:
data['location'].value_counts()

location
Whitefield                                      540
Sarjapur  Road                                  399
Electronic City                                 302
Kanakpura Road                                  273
Thanisandra                                     234
                                               ...
Maragondana Halli, kr puram, old madras road      1
Chikkajala                                        1
Udayagiri                                         1
pavitra paradise                                  1
Chikbasavanapura                                  1
Name: count, Length: 1306, dtype: int64

In [32]:
data['location']=data['location'].apply(lambda x: x.strip())
location_count = data['location'].value_counts()

In [33]:
location_count_less_10 = location_count[location_count <=10]
location_count_less_10

location
1st Block Koramangala     10
Dairy Circle              10
Nagadevanahalli           10
Sadashiva Nagar           10
Naganathapura             10
                          ..
Xavier Layout              1
Ramanagara Channapatna     1
Maheswari Nagar            1
Hsr layout sector3         1
Thyagraj Nagar             1
Name: count, Length: 1054, dtype: int64

In [34]:
data['location'] = data['location'].apply(lambda x: 'other' if x in location_count_less_10 else x)

In [35]:
data['location'].value_counts()

location
other                        2886
Whitefield                    541
Sarjapur  Road                399
Electronic City               304
Kanakpura Road                273
                             ...
Tindlu                         11
Marsur                         11
2nd Phase Judicial Layout      11
Thyagaraja Nagar               11
HAL 2nd Stage                  11
Name: count, Length: 242, dtype: int64

In [36]:
data.describe()

         total_sqft          bath         price           bhk  price_per_sqft
count  13274.000000  13320.000000  13320.000000  13304.000000    1.327400e+04
mean    1559.626694      2.688814    112.565627      2.803743    7.907501e+03
std     1238.405258      1.338754    148.971674      1.294974    1.064296e+05
min        1.000000      1.000000      8.000000      1.000000    2.678298e+02
25%     1100.000000      2.000000     50.000000      2.000000    4.266865e+03
50%     1276.000000      2.000000     72.000000      3.000000    5.434306e+03
75%     1680.000000      3.000000    120.000000      3.000000    7.311746e+03
max    52272.000000     40.000000   3600.000000     43.000000    1.200000e+07

In [37]:
(data['total_sqft']/data['bhk']).describe()

count    13258.000000
mean       574.420590
std        387.584212
min          0.250000
25%        473.333333
50%        552.250000
75%        625.000000
max      26136.000000
dtype: float64

In [38]:
data =data[((data['total_sqft']/data['bhk']) >= 300)]

In [39]:
data.shape

(12514, 7)

In [40]:
data.describe()

         total_sqft          bath         price           bhk  price_per_sqft
count  12514.000000  12514.000000  12514.000000  12514.000000    12514.000000
mean    1593.746383      2.560253    111.398333      2.651670     6307.367132
std     1261.351669      1.078441    152.098807      0.977025     4160.773691
min      300.000000      1.000000      9.000000      1.000000      267.829813
25%     1116.000000      2.000000     49.000000      2.000000     4210.762120
50%     1300.000000      2.000000     70.000000      3.000000     5295.073227
75%     1700.000000      3.000000    115.000000      3.000000     6916.666667
max    52272.000000     16.000000   3600.000000     16.000000   176470.588235

In [41]:
data.price_per_sqft.describe()

count     12514.000000
mean       6307.367132
std        4160.773691
min         267.829813
25%        4210.762120
50%        5295.073227
75%        6916.666667
max      176470.588235
Name: price_per_sqft, dtype: float64

In [42]:
def remove_outliner_sqft(df):
    df_output = pd.DataFrame()
    for key, subdf in df.groupby('location'):
        m = np.mean(subdf.price_per_sqft)

        st = np.std(subdf.price_per_sqft)
        gen_dg= subdf[
        (subdf.price_per_sqft > (m-st)) & 
        (subdf.price_per_sqft <= (m+st))
        ]
        df_output = pd.concat([df_output, gen_dg], ignore_index =True)

    return df_output
data =remove_outliner_sqft(data)
data.describe()

         total_sqft          bath         price           bhk  price_per_sqft
count  10287.000000  10287.000000  10287.000000  10287.000000    10287.000000
mean    1507.548674      2.471663     91.250302      2.574900     5659.971734
std      879.955401      0.979644     86.316523      0.898074     2265.519556
min      300.000000      1.000000     10.000000      1.000000     1250.000000
25%     1109.000000      2.000000     49.000000      2.000000     4250.000000
50%     1285.000000      2.000000     67.000000      2.000000     5176.470588
75%     1650.000000      3.000000    100.000000      3.000000     6428.571429
max    30400.000000     16.000000   2200.000000     16.000000    24509.803922

In [43]:
data.describe()

         total_sqft          bath         price           bhk  price_per_sqft
count  10287.000000  10287.000000  10287.000000  10287.000000    10287.000000
mean    1507.548674      2.471663     91.250302      2.574900     5659.971734
std      879.955401      0.979644     86.316523      0.898074     2265.519556
min      300.000000      1.000000     10.000000      1.000000     1250.000000
25%     1109.000000      2.000000     49.000000      2.000000     4250.000000
50%     1285.000000      2.000000     67.000000      2.000000     5176.470588
75%     1650.000000      3.000000    100.000000      3.000000     6428.571429
max    30400.000000     16.000000   2200.000000     16.000000    24509.803922

In [44]:
def remove_bhk_outlier(df):
    exclude_indices = np.array([])

    for location, location_df in df.groupby('location'):
        bhk_stats = {}

        # Step 1: Calculate mean & count for each BHK in that location
        for bhk, bhk_df in location_df.groupby('bhk'):
            bhk_stats[bhk] = {
                'mean': np.mean(bhk_df.price_per_sqft),
                'std': np.std(bhk_df.price_per_sqft),
                'count': bhk_df.shape[0]
            }

        # Step 2: Compare current BHK with previous BHK
        for bhk, bhk_df in location_df.groupby('bhk'):
            stats = bhk_stats.get(bhk - 1)

            if stats and stats['count'] > 5:
                exclude_indices = np.append(
                    exclude_indices,
                    bhk_df[bhk_df.price_per_sqft < stats['mean']].index.values
                )

    return df.drop(exclude_indices, axis='index')

In [45]:
data = remove_bhk_outlier(data)

In [46]:
data.shape

(7354, 7)

In [47]:
data

,location,size,total_sqft,bath,price,bhk,price_per_sqft
0,1st Block Jayanagar,4 BHK,2850.0,4.0,428.0,4.0,15017.543860
1,1st Block Jayanagar,3 BHK,1630.0,3.0,194.0,3.0,11901.840491
2,1st Block Jayanagar,3 BHK,1875.0,2.0,235.0,3.0,12533.333333
3,1st Block Jayanagar,3 BHK,1200.0,2.0,130.0,3.0,10833.333333
4,1st Block Jayanagar,2 BHK,1235.0,2.0,148.0,2.0,11983.805668
...,...,...,...,...,...,...,...
10278,other,2 BHK,1200.0,2.0,70.0,2.0,5833.333333
10279,other,1 BHK,1800.0,1.0,200.0,1.0,11111.111111
10282,other,2 BHK,1353.0,2.0,110.0,2.0,8130.081301
10283,other,1 Bedroom,812.0,1.0,26.0,1.0,3201.970443
10286,other,4 BHK,3600.0,5.0,400.0,4.0,11111.111111

In [48]:
data.drop(columns = ['size' ,'price_per_sqft'],inplace =True)

In [49]:
data.head()

              location  total_sqft  bath  price  bhk
0  1st Block Jayanagar      2850.0   4.0  428.0  4.0
1  1st Block Jayanagar      1630.0   3.0  194.0  3.0
2  1st Block Jayanagar      1875.0   2.0  235.0  3.0
3  1st Block Jayanagar      1200.0   2.0  130.0  3.0
4  1st Block Jayanagar      1235.0   2.0  148.0  2.0

In [50]:
data.to_csv("Cleaned_data.csv")

In [51]:
x = data.drop(columns = ['price'])
y = data['price']

In [52]:
from sklearn.preprocessing import StandardScaler , OneHotEncoder
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression , Lasso , Ridge
from sklearn.compose import make_column_transformer
from sklearn.pipeline import make_pipeline
from sklearn.metrics import r2_score

In [53]:
x_train ,x_test, y_train , y_test = train_test_split(x , y ,test_size =2, random_state =20)

In [54]:
print(x_train.shape)

(7352, 4)

In [55]:
print(x_test.shape)

(2, 4)

In [56]:
columns_trans = make_column_transformer((OneHotEncoder(sparse_output = False) , ['location']),
                                        remainder ='passthrough')

In [57]:
OneHotEncoder(handle_unknown='ignore', sparse_output=False)

OneHotEncoder(handle_unknown='ignore', sparse_output=False)

In [58]:
scaler = StandardScaler()

In [59]:
lr =LinearRegression()

In [60]:
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression

lr = make_pipeline(
    StandardScaler(),
    LinearRegression()
)
#pipe = make_pipeline(column_trans , scaler, lr)

In [61]:
from sklearn.preprocessing import StandardScaler

pipe = make_pipeline(
    columns_trans,
    StandardScaler(),
    LinearRegression()
)

In [62]:
pipe.fit(x_train ,y_train)

C:\Users\USER\anaconda3\Lib\site-packages\sklearn\compose\_column_transformer.py:1667: FutureWarning:
The format of the columns of the 'remainder' transformer in ColumnTransformer.transformers_ will change in version 1.7 to match the format of the other transformers.
At the moment the remainder columns are stored as indices (of type int). With the same ColumnTransformer configuration, in the future they will be stored as column names (of type str).
To use the new behavior now and suppress this warning, use ColumnTransformer(force_int_remainder_cols=False).

  warnings.warn(

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('onehotencoder',
                                                  OneHotEncoder(sparse_output=False),
                                                  ['location'])])),
                ('standardscaler', StandardScaler()),
                ('linearregression', LinearRegression())])

In [63]:
y_pred_lr = pipe.predict(x_test)

In [64]:
r2_score(y_test ,y_pred_lr)

-17.526518087539298

In [65]:
lasso = Lasso()

In [66]:
pipe =make_pipeline( columns_trans , scaler , lasso)

In [67]:
pipe.fit(x_train , y_train)

C:\Users\USER\anaconda3\Lib\site-packages\sklearn\compose\_column_transformer.py:1667: FutureWarning:
The format of the columns of the 'remainder' transformer in ColumnTransformer.transformers_ will change in version 1.7 to match the format of the other transformers.
At the moment the remainder columns are stored as indices (of type int). With the same ColumnTransformer configuration, in the future they will be stored as column names (of type str).
To use the new behavior now and suppress this warning, use ColumnTransformer(force_int_remainder_cols=False).

  warnings.warn(

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('onehotencoder',
                                                  OneHotEncoder(sparse_output=False),
                                                  ['location'])])),
                ('standardscaler', StandardScaler()), ('lasso', Lasso())])

In [68]:
y_pred_lasso = pipe.predict(x_test)
r2_score(y_test , y_pred_lasso)

-0.11793570984512103

In [69]:
ridge = Ridge()

In [70]:
pipe = make_pipeline(columns_trans , scaler , ridge)

In [71]:
pipe.fit(x_train ,y_train)

C:\Users\USER\anaconda3\Lib\site-packages\sklearn\compose\_column_transformer.py:1667: FutureWarning:
The format of the columns of the 'remainder' transformer in ColumnTransformer.transformers_ will change in version 1.7 to match the format of the other transformers.
At the moment the remainder columns are stored as indices (of type int). With the same ColumnTransformer configuration, in the future they will be stored as column names (of type str).
To use the new behavior now and suppress this warning, use ColumnTransformer(force_int_remainder_cols=False).

  warnings.warn(

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('onehotencoder',
                                                  OneHotEncoder(sparse_output=False),
                                                  ['location'])])),
                ('standardscaler', StandardScaler()), ('ridge', Ridge())])

In [72]:
y_pred_ridg = pipe.predict(x_test)
r2_score(y_test , y_pred_ridg)

-17.526506085054976

In [73]:
print("r22",r2_score(y_test ,y_pred_lr))
print("Ridge" , r2_score(y_test , y_pred_ridg))
print("lasso" ,r2_score(y_test , y_pred_lasso))

r22 -17.526518087539298
Ridge -17.526506085054976
lasso -0.11793570984512103

In [74]:
import pickle

In [76]:
pickle.dump(pipe , open("RidgeModel.pkl" , 'wb'))